### PR TITLE
fixed inCross offset and signatures

### PR DESCRIPTION
**Pull request by ericek111**
again, how to fix: https://github.com/McSwaggens/linux-csgo-external/pull/49

### CODE REVIEW

**Comment by henrydatei** [comment]
Thanks a lot. Works for me

**Comment by citizen46** [comment]
Great! sorry for replying late, just seen now.

**Comment by citizen46** [comment]
@ericek111 It's not working. the Triggerbot.

**Comment by citizen46** [comment]
@ericek111 It's not working. the Triggerbot. Please help.

**Comment by ericek111** [comment]
Learn to play without triggerbot. ¯\_(ツ)_/¯

**Comment by citizen46** [comment]
@ericek111 was this supposed to be your final words.

**Comment by citizen46** [comment]
> Learn to play without triggerbot. ¯_(ツ)_/¯

I respect the fact that you have skills, rather you can do things which i can't. As i've never been in technical skills for computer, therefore i requested your help in fixing that piece of software. 

Thanks for whatever reply you gave, I'm glad that you helped us alot of times by fixing the code and getting us new offsets.

As this software have functions like wallhack, radar, triggerbot.
This is why i sent a request on this thread for you to fix the triggerbot function.

If you can't or you're tired by this project you're free to speak about it, rather than suggesting me to learn to play this way or that way.

I hope you get to understand.

**Comment by bryantwilliam** [comment]
> 
> 
> > Learn to play without triggerbot. ¯_(ツ)_/¯
> 
> I respect the fact that you have skills, rather you can do things which i can't. As i've never been in technical skills for computer, therefore i requested your help in fixing that piece of software.
> 
> Thanks for whatever reply you gave, I'm glad that you helped us alot of times by fixing the code and getting us new offsets.
> 
> As this software have functions like wallhack, radar, triggerbot.
> This is why i sent a request on this thread for you to fix the triggerbot function.
> 
> If you can't or you're tired by this project you're free to speak about it, rather than suggesting me to learn to play this way or that way.
> 
> I hope you get to understand.

Passive aggressive bitching to someone giving you code maintenance for free.

**Comment by ericek111** [comment]
I meant it. Why do you care about triggerbot so much? It's the most non-legit feature in this cheat, makes you look so obvious and it doesn't even help you much in game. If you're willing to use trigger, you might as well switch to https://github.com/LWSS/Fuzion - internal cheat with a lot more features.

Anyway. It seems that the force attack pattern is right on the boundary of two read buffers (MapModuleMemoryRegion::find). The pattern finder is probably flawed and needs to be fixed. I will look into it later this day.

**Comment by citizen46** [comment]
Thanks for everything, I've been using it for almost 2 years.

**Comment by citizen46** [comment]
I can't use Fuzion, it got me Untrusted couple of times and Vac 2 times.

**Comment by citizen46** [comment]
Been using this simple cheat for almost 2y I didn't got banned vac/Untrusted.

**Comment by ericek111** [comment]
all right, I have added a signature for the entity-in-crosshair offset (target ID). It should last a long time.

**Comment by citizen46** [comment]
Thanks so much for the work you did, I'll remember you in my prayers.

**Review by Psyquoquack — APPROVED** [review]

**Pull request closed without merging**
